[INVE-17771] Simplify deps
sirensolutions/eslint-plugin pull request #31
Opened 2022-07-21 14:38 UTC by fabiocorneti

- Sets yarn as the package manager
- Removes the dependency on `@elastic/eslint-config-kibana`
- Sets all runtime dependencies to be peer dependencies
- Upgrades existing dependencies

2022-07-21 14:57 UTC, Blakko approved these changes

2022-07-21 15:21 UTC, daniele-pini requested changes
Is .yarn/releases/yarn-3.2.1.cjs really necessary?

2022-07-21 17:02 UTC, fabiocorneti commented
Yes, yarn itself must be there.

2022-07-22 07:22 UTC, daniele-pini approved these changes

2022-07-22 08:42 UTC, merged